spec:
  template:
    spec:
      containers:
        - name: ubip-demo-rest-2-soap
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPTIONS
              value: '-Dspring.profiles.active=qa -Djava.library.path=/var/lib/common-config/current/ubip-deps/saplib'
            - name: SNC_LIB
              value: /var/lib/common-config/current/ubip-deps/saplib/snc_linux/libsapcrypto.so
            - name: SECUDIR
              value: /var/lib/common-config/current/ubip-deps/saplib
          ports:
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 9779
              name: promethus
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
              name: http
            - containerPort: 8081
              protocol: TCP
              name: management
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /var/lib/common-config
              name: common-config
      volumes:
        - name: common-config
          persistentVolumeClaim:
            claimName: ubip-config-claim
